server:
  port: 8070

spring:
  redis:
    host: localhost
    port: 6379
    expire: 1800
    timeout: 0
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  data:
    mongodb:
      host: localhost
      database: bicycle
      port: 27017
#      username: zfgxpt
#      password: zfgxpt